name: Build, Push, and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ezio22/argocd-node-app:latest

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure SonarQube analysis runs after the Docker push
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        host-url: ${{ secrets.SONAR_HOST_URL }}
        login: ${{ secrets.SONAR_TOKEN }}